name: CHDB CLI Builder

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Release Version Tag'
        required: true
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Binary
      run: |
        pyinstaller chdb-cli.py --strip --noupx
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            ./dist/chdb-cli/chdb-cli
        tag_name: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
        release_name: chdbcli_v${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
        draft: false
        prerelease: false
        overwrite: true   
 
